---
- name: "Optiver Day 1 Operations"
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - "vars/vaulting.yml"
    - "vars/defaults.yml"
    # - "vars/environment.yml"
    # - "vars/svm_template.yml"
    # - "vars/svm.yml"

  roles:
    - { role: optiver_ontap_svm_create, qtask: facts }
    - { role: optiver_ontap_svm_create, qtask: deploy }
    - { role: optiver_ontap_svm_create, qtask: lifs }
