- set_fact:
    auth: &auth
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

### 01
- name: Create FlexVol
  netapp.ontap.na_ontap_volume:
    state: present
    name: "{{ volume_name }}"
    is_infinite: False
    aggregate_name: "{{ aggregate_name }}"
    size: "{{ volume_size }}"
    size_unit: "{{ size_unit }}"
    space_guarantee: none
    percent_snapshot_space: "{{ percent_snapshot_space }}"
    vserver: "{{ svm_name }}"
    wait_for_completion: True
    comment: ansible created volume
    <<: *auth
  # when: "volume_name not in vol_list"
  delegate_to: localhost


### 02
- name: Modify FlexVol
  netapp.ontap.na_ontap_volume:
    state: present
    name: "{{ volume_name }}"
    snapdir_access: no
    snapshot_auto_delete:
      state: "on"
      commitment: destroy
      defer_delete: none
      prefix: ''
      trigger: volume
      target_free_space: 10
      destroy_list: none
      delete_order: oldest_first
    vserver: "{{ svm_name }}"
    wait_for_completion: True
    comment: ansible created volume
    <<: *auth
  # when: "volume_name not in vol_list"
  delegate_to: localhost


- name: Add Junction Path
  netapp.ontap.na_ontap_volume:
    state: present
    name: "{{ volume_name }}"
    junction_path: "/{{ volume_name }}"
    export_policy: "{{ export_policy }}"
    vserver: "{{ svm_name }}"
    wait_for_completion: True
    comment: ansible created volume
    <<: *auth
  when:
    # - "volume_name not in vol_list"
    - use == "nfs"
  delegate_to: localhost
