---

- set_fact:
    auth: &auth
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

### 01. (Schedule)  - cluster wide
- name: Create Job Schedule
  na_ontap_job_schedule:
   state: present
   name: "{{ item.name }}"
   job_minutes: "{{ item.job_minutes }}"
   job_hours: "{{ item.job_hours }}"
   job_days_of_week: "{{ item.job_days_of_week }}"
   <<: *auth
  with_items:
   - "{{ job_schedules }}"
  ignore_errors: true
  register: job_schedule
  delegate_to: localhost

### 02. (Snapshot Policy) - cluster wide
#Snapshot Policy
- name: Create Snapshot policy
  netapp.ontap.na_ontap_snapshot_policy:
    state: present
    name: "{{ item.name }}"
    schedule: "{{ item.schedule }}"
    count: "{{ item.count }}"
    enabled: True
    <<: *auth
  loop: "{{ snapshot_policies }}"
  loop_control:
    label: "{{ item.name }}"
  ignore_errors: true
  register: snapshot_policy
  delegate_to: localhost

## 1- Create Vlans () - vlan's can also be part of day 1, but can be diff for cluster types (diff ports etc...)... so automate or not ??
# - name: create VLANs
#   netapp.ontap.na_ontap_net_vlan:
#     state: present
#     vlanid: "{{ item.vlan_id }}"
#     node: "{{ item.node_name }}"
#     parent_interface: "{{ item.int_grp_name }}"
#     <<: *auth
#   with_items: "{{ vlans_list }}"
#   delegate_to: localhost
#   when:
#     - allowed_protocols == "nfs"

## 2-  Create broadcast domains - could be day 1 automation, but better to ask netapp consultant, can quickly be complex to automate
# - name: create broadcast domain
#   netapp.ontap.na_ontap_broadcast_domain:
#     state: present
#     <<: *auth
#     name: "{{ item.1 }}"
#     mtu: 9000
#     #ipspace: Default
#     ports: "{{ item.0.node_name }}:{{ item.0.vlan_name }}"
#   loop: "{{ vlans_list | product(broadcast_domain) | list }}"
#   when:
#     - allowed_protocols == "nfs"
#     - item.1 not in bd_final_list
#     - item.1[-3:] == item.0.vlan_id
#   delegate_to: localhost


# ## 3- Add more ports to broadcast domains
# - name: add broadcast domain ports
#   netapp.ontap.na_ontap_broadcast_domain_ports:
#     state: present
#     <<: *auth
#     broadcast_domain: "{{ item.1 }}"
#     ports: "{{item.0.node_name }}:{{ item.0.vlan_name }}"
#   loop: "{{ vlans_list | product(broadcast_domain) | list }}"
#   when:
#     - allowed_protocols == "nfs"
#     - item.1[-3:] == item.0.vlan_id
#   delegate_to: localhost

## 02. aQoS Policy Group
##- name: aQoS Policy Group
##  na_ontap_qos_adaptive_policy_group:
##   state: present
##    name:
##    vserver:
##    absolute_min_iops:
##    expected_iops:
##    peak_iops:
##    peak_iops_allocation:
##    <<: *auth
##  delegate_to: localhost

### 13. Create LDAP
## Pendiente tarea 10a
#- name: Create LDAP
#  na_ontap_ldap:
#    state: present
#    name:
#    vserver:
#    skip_config_validation:
#    <<: *auth
#  delegate_to: localhost

# snapshots policies can also be per vserver, but we use cluster wide
### 15. (Snapshot Policy Vserver)
#Snapshot Policy
# condicional no ejecutar si FCP
#- name: Create Snapshot policy
#  na_ontap_snapshot_policy:
#    state: present
#    name: "{{ item.name }}"
#    schedule: "{{ item.schedule }}"
#    vserver: "{{ svm_match | default(svm_name) }}"
#    count: "{{ item.count }}"
#    enabled: True
#    <<: *auth
#  with_items:
#    - "{{ snapshot_policies }}"
#  ignore_errors: true
#  register: snapshot_policy
#  delegate_to: localhost
