---

- set_fact:
    auth: &auth
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

- name: Create certificate
  netapp.ontap.na_ontap_security_certificates:
    state: present
    common_name: "api_user"
    name: "api_user"
    type: client_ca
    vserver: "{{cluster_name}}"
    public_certificate: "{{ api_user_certificate }}"
    <<: *auth
  register: cert_create
  no_log: true
  delegate_to: localhost

- name: Create api user
  na_ontap_user:
    state: present
    name: "api_user"
    authentication_method: cert
    applications: "ontapi,http"
    role_name: "admin"
    lock_user: false
    vserver: "{{cluster_name}}"
    <<: *auth
  register: create_api_user
  no_log: false
  delegate_to: localhost


- name: Change admin password
  na_ontap_user:
    state: present
    name: admin
    authentication_method: password
    applications: "ontapi,ssh,http,console,service-processor"
    role_name: "admin"
    set_password: "{{ admin_password }}"  #This is an example. Must be included in ansible vault variable"
    lock_user: false
    vserver: "{{cluster_name}}"
    <<: *auth
  register: ch_admin_password
  no_log: false
  delegate_to: localhost
